### ISSUE TITLE
Might be time to update the project

### ISSUE THREAD

**Issue by ekdysis** [liamreardon/windmill#2]
Hello Liam, I attempted to run your project this morning on Xcode 12.0.1 

Got it to work after doing a few things.

**Deleting the committed files from the Config folder such as:**
* `Development.xcconfig`
* `Staging.xcconfig`
* `Production.xcconfig`

And running a `pod update` as there was a build error in the `NextLevel.swift` file regarding the AVFoundation framework. 

Also, it might be good to add in your `README.md` file that anyone checking out this project will need to add their own `credentials.plist` file into the project for it to successfully run after setting up their Client ID -- this is obviously pretty self-explanatory but might not be for beginners and onlookers who are curious and eager to run your project.

Otherwise, great job Liam and looking forward to seeing additional updates on this well-architected project!

**Comment by liamreardon** [comment]
Hey @alex-x-x-x-x,

Appreciate the feedback! I'll update the config settings / the `README.md` file soon with the things you mentioned.
