### ISSUE TITLE
mangodb help 

### ISSUE THREAD

**Issue by maxtaunton** [liamreardon/windmill#3]
I am receiving a issue in Xcode `NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://192.168.1.48:27017/api/auth/login, NSErrorFailingURLKey=http://192.168.1.48:27017/api/auth/login, _kCFStreamErrorDomainKey=1}
2021-01-01 15:57:44.972593-0700 windmill[14161:864116] [connection] nw_socket_handle_socket_event [C4:2] Socket SO_ERROR [61: Connection refused]` and I don't understand it, any help?

**Comment by liamreardon** [comment]
@maxtaunton Are you running the server? `windmill-backend`

**Comment by maxtaunton** [comment]
yes, I am using a Raspberry pi to run the sever

**Comment by maxtaunton** [comment]
I am running the server on my network and I can go to the ip address of the device and see 'It looks like you are trying to access MongoDB over HTTP on the native driver port.'

**Comment by maxtaunton** [comment]
@liamreardon I am running the server on my network and I can go to the ip address of the device and see 'It looks like you are trying to access MongoDB over HTTP on the native driver port.'

**Comment by liamreardon** [comment]
@maxtaunton Are you using a local mongo instance? If the problem persists another solution would be to run up a free mongo instance on https://www.mongodb.com/cloud/atlas, and use that as database uri.

**Comment by liamreardon** [comment]
@maxtaunton This may be of help also: https://stackoverflow.com/questions/23446876/cannot-access-mongodb-through-browser-it-looks-like-you-are-trying-to-access-m

**Comment by maxtaunton** [comment]
is there a way to use local mangodb with windmill?

**Comment by maxtaunton** [comment]
@liamreardon is there a way to use a local mangodb Database with windmill?

**Comment by maxtaunton** [comment]
@liamreardon I have tried atlas and a local server and I keep getting the same error message `NSLocalizedDescription=The network connection was lost., NSErrorFailingURLStringKey=http://cluster0-shard-00-02.hvewa.mongodb.net:27017/api/auth/login, NSErrorFailingURLKey=http://cluster0-shard-00-02.hvewa.mongodb.net:27017/api/auth/login, _kCFStreamErrorDomainKey=4}
` for atlas and `NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://192.168.1.48:27017/api/auth/login, NSErrorFailingURLKey=http://192.168.1.48:27017/api/auth/login, _kCFStreamErrorDomainKey=1} 2021-01-01 15:57:44.972593-0700 windmill[14161:864116] [connection] nw_socket_handle_socket_event [C4:2] Socket SO_ERROR [61: Connection refused]` for local. is there any settings I need to add to my atlas server to get this project working?

**Comment by liamreardon** [comment]
@maxtaunton It seems like you're trying to connect to the server using the mongo uri, the iOS app needs to connect to endpoint `http://localhost:8080/api/auth/login`

**Comment by maxtaunton** [comment]
I just tried setting that in the config.plist and I get the same message

**Comment by liamreardon** [comment]
@maxtaunton Just to confirm again, you are running the Golang API on the raspberry pi, correct?

**Comment by maxtaunton** [comment]
no I used this [https://developer.mongodb.com/how-to/mongodb-on-raspberry-pi](url) to install it on the raspi

**Comment by liamreardon** [comment]
@maxtaunton Right, but you will also need to run `windmill-backend` in order for the app to work: https://github.com/liamreardon/windmill#go

**Comment by maxtaunton** [comment]
I just updated the touch.env file with my raspi local ip address and got this error `2021/01/02 08:58:14 No .env file found
2021/01/02 08:58:14 No .env file found
2021/01/02 08:58:14 Database URI does not exist.`

**Comment by liamreardon** [comment]
@maxtaunton the file should just be called `.env`, rename it from `touch.env` to `.env`.

**Comment by maxtaunton** [comment]
ok I just did that should I run `go run main.go`

**Comment by liamreardon** [comment]
@maxtaunton Yup `go run main.go` will start the server, then the iOS app will be able to connect to it via `http://localhost:8080/api`

**Comment by maxtaunton** [comment]
I just did that and I keep getting the same error in Xcode when using iOS simulator

**Comment by maxtaunton** [comment]
@liamreardon I just did that and I keep getting the same error in Xcode when using iOS simulator

**Comment by liamreardon** [comment]
@maxtaunton copy and paste your Config.plist file and .env file here, want to confirm if everything is correct

**Comment by maxtaunton** [comment]
@liamreardon 
`ROOT_URL = http://localhoast:8080`
`BUCKET_URL = https://blixer.s3.us-east-1.amazonaws.com`
`GOOGLE_CLIENT_ID = 892808974997-evbbmvrqahipfu9769cgenvadrr37d9i.apps.googleusercontent.com`
`APP_BUNDLE_ID = io.blixer.windmill`
`APP_NAME = windmill`
that is my config .plist

**Comment by maxtaunton** [comment]
@liamreardon 
`DB_URI=mongodb://192.168.1.48:27017

AWS_S3_BASE=https://blixer.s3.us-east-1.amazonaws.com/users/

AWS_S3_REGION=us-east-1

AWS_S3_BUCKET=blixer
`
that is my `.env` file

**Comment by maxtaunton** [comment]
@liamreardon
DB_URI=mongodb://192.168.1.48:27017
AWS_S3_BASE=https://blixer.s3.us-east-1.amazonaws.com/users/
AWS_S3_REGION=us-east-1
AWS_S3_BUCKET=blixer

that is my .env file

**Comment by maxtaunton** [comment]
@liamreardon is everything correct, if not please tell me where the problem is.

**Comment by maxtaunton** [comment]
@liamreardon is everything correct? if not please tell me where the problem is.

**Comment by maxtaunton** [comment]
@liamreardon is everything correct? if not please tell me where the problem is.

**Comment by liamreardon** [comment]
@maxtaunton change `ROOT_URL = http://localhoast:8080` to `ROOT_URL = http://localhost:8080`

**Comment by liamreardon** [comment]
@maxtaunton the issue is specific to running server and mongo on Raspberry Pi

**Comment by maxtaunton** [comment]
when I choose a profile photo and press save it crashes

**Comment by maxtaunton** [comment]
should I try atlas?

**Comment by maxtaunton** [comment]
I just took a video of the process and it try's to bring me to the feed screen but It crashes (I think because there is not any videos)

**Comment by liamreardon** [comment]
@maxtaunton Yes this is likely due to the mongo connection issues, what are the error logs for this?

**Comment by maxtaunton** [comment]
the error is 
`Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
windmill was compiled with optimization - stepping may behave oddly; variables may not be available.
(lldb) `

**Comment by maxtaunton** [comment]
and `Thread 9: Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value`

**Comment by maxtaunton** [comment]
I can send a screen recording

**Comment by maxtaunton** [comment]
@liamreardon I can send a screen recording of me doing trying

**Comment by maxtaunton** [comment]
@liamreardon when I try to build it to my iPhone XR I get this error 
`Command PhaseScriptExecution failed with a nonzero exit code
`

**Comment by maxtaunton** [comment]
@liamreardon  I got this on for `#1	0x0000000107bc12f0 in closure #1 in HomeViewController.getFeed() at /Users/maxtaunton/Downloads/windmill-master-4/windmill-ios/windmill/Controllers/Home/HomeViewController.swift:133
`
`Thread 3: Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value`

**Comment by liamreardon** [comment]
@maxtaunton What is error when trying to upload profile picture? If there are no videos, it shouldn't crash, it should just be an empty feed

**Comment by maxtaunton** [comment]
it doesn't do that anymore but I can't upload a video because I can't get the app to my iPhone

**Comment by maxtaunton** [comment]
@liamreardon it doesn't do that anymore but I can't upload a video because I can't get the app to my iPhone

**Comment by liamreardon** [comment]
@maxtaunton You will need to run on iOS device in order to use all video features

**Comment by maxtaunton** [comment]
I can’t get the app to build to my iPhone XR

**Comment by maxtaunton** [comment]
I can’t get the app to build to my iPhone XR and I get the ` command PhaseScriptExecution failed with a nonzero exit code` error

**Comment by maxtaunton** [comment]
@liamreardon  I can’t get the app to build to my iPhone XR and I get the `command PhaseScriptExecution failed with a nonzero exit code` error

**Comment by maxtaunton** [comment]
@liamreardon I can’t get the app to build to my iPhone XR and I get the command PhaseScriptExecution failed with a nonzero exit code error
